// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vykyfktmbjcexspcpbxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5a3lma3RtYmpjZXhzcGNwYnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDY0MjQsImV4cCI6MjA3NDU4MjQyNH0.YelBrF9zc0-BICuOyMKnxNYj77tQUKH0OEcKzgy4m5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});